version: '2'

volumes:
  data:

services:
  jupyter:
    build: ./docker
    volumes:
      - ./notebooks:/notebooks
    ports:
      - "8888:8888"

  mongo:
    image: mongo:3.4
    volumes:
      - data:/data
